# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tom Yang's Creative Factory
brand: TY Creative Factory
email: xy2286@columbia.edu
description: > #
          Full-stack Web Developer!
          Just a freshman in the field, One day I will become someone!


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://TomYang1993.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  TomYang1993

# Build settings
markdown: kramdown

#set liquid warnings
liquid:
  error_mode: warn

#Include gems

#img path
img_path: '/assets/img'

#sections data
sections:
  - id: 'about'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'
