# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tom Yang's Creative Factory
email: xy2286@columbia.edu
description: > #
          A New Ruby Developer!
          Just a freshman in the field, One day I will become someone!


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://TomYang1993.github.io." # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  TomYang1993

# Build settings
markdown: kramdown

#Include gems
